$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
allowCompoundWords: true
useGitignore: true
dictionaries:
  - python
words:
  - ASGI
  - ioreg
  - IOUSB
  - kabankz
  - libstdc
  - lsusb
  - PYTHONUNBUFFERED
  - scannability
  - taplo
  - tolower
  - toupper
  - unstarted
