$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
allowCompoundWords: true
useGitignore: true
dictionaries:
  - python
words:
  - ASGI
  - dotenv
  - libstdc
  - PYTHONUNBUFFERED
  - tolower
  - toupper
  - unstarted
