[project]
name = "papercut"
version = "0.1.0"
description = "Print your tickets on a real receipt printer"
readme = "README.md"
authors = [{ name = "KaBanks", email = "hi@krabby.dev" }]
license = "MIT"
requires-python = ">=3.14"
dependencies = [
  "fastapi>=0.120.0",
  "uvicorn[standard]>=0.38.0",
  "python-dotenv>=1.2.1",
  "python-escpos>=3.1",
]
